### PR TITLE
Create form to deactivate chapter

### PR DESCRIPTION
**Pull request by Mariatta**

### CODE REVIEW

**Review by terezaif — APPROVED** [review]
Looks good! 
Will we on our side implement a policy of checking? like what is to stop malicious users from deactivating existing chapters?

should we have a double verification by also asking for the slack handle?

**Comment by Mariatta** [comment]
That's good point. I can make the form such that they have to login with the chapter's email address in order to request the deactivation. What do you think?

**Comment by terezaif** [comment]
That's a good idea!

**Comment by lorenanicole** [comment]
Great question  @terezaif ! I think that what you suggested @Mariatta would resolve any issues  on malicious activity.

**Pull request merged**
